# Documentation: https://docs.codecov.io/docs/codecov-yaml

## Avoid "Missing base report"
## https://github.com/codecov/support/issues/363
## https://docs.codecov.io/docs/comparing-commits
#allow_coverage_offsets: true

## Avoid Report Expired
## https://docs.codecov.io/docs/codecov-yaml#section-expired-reports
#max_report_age: off

# https://docs.codecov.io/docs/coverage-configuration
coverage:
    range: 60..85
    round: down
    precision: 2

    status:
        project:
            default:
                # basic
                target: 70%
        patch:
            default:
                # basic
                target: 70%