name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
    - name: Update Codecov
      uses: codecov/codecov-action@v1
    - name: Publish WebUI WebAssembly
      run: dotnet publish -c Release "./src/Mazes.WebUI" -o publishoutput
    - name: Deploy to Netlify
      uses: netlify/actions/cli@master #uses Netlify Cli actions
      with:
        args: deploy --dir=publishoutput/wwwroot --prod #push this folder to Netlify
      env: # These are the environment variables added in GitHub Secrets for this repo
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}